# Usa la imagen oficial de Python
FROM python:3.11-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de dependencias
COPY requirements.txt .

# Instala las dependencias necesarias y gunicorn
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir gunicorn

# Copia todo el código de la aplicación
COPY . .

# Build-time ARGs → runtime ENV vars (override with --build-arg on each build)
ARG LLM_PROVIDER
ENV LLM_PROVIDER=$LLM_PROVIDER

ARG GOOGLE_API_KEY
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY

ARG GEMINI_MODEL
ENV GEMINI_MODEL=$GEMINI_MODEL

ARG SANDBOX_DISPLAY_NAME
ENV SANDBOX_DISPLAY_NAME=$SANDBOX_DISPLAY_NAME

ARG AGENT_ENGINE_DISPLAY_NAME
ENV AGENT_ENGINE_DISPLAY_NAME=$AGENT_ENGINE_DISPLAY_NAME

ARG PROJECT_ID
ENV PROJECT_ID=$PROJECT_ID

ARG LOCATION
ENV LOCATION=$LOCATION

ARG OPENAI_MODEL
ENV OPENAI_MODEL=$OPENAI_MODEL

ARG VECTOR_STORE_ID
ENV VECTOR_STORE_ID=$VECTOR_STORE_ID

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY

ARG PINECONE_API_KEY
ENV PINECONE_API_KEY=$PINECONE_API_KEY

ARG PINECONE_INDEX_NAME
ENV PINECONE_INDEX_NAME=$PINECONE_INDEX_NAME

ARG PINECONE_NAMESPACE
ENV PINECONE_NAMESPACE=$PINECONE_NAMESPACE

ARG PINECONE_EMBEDDING_MODEL
ENV PINECONE_EMBEDDING_MODEL=$PINECONE_EMBEDDING_MODEL

ARG STRAVA_CLIENT_ID
ENV STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID

ARG STRAVA_CLIENT_SECRET
ENV STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET

ARG STRAVA_OAUTH_STATE_SECRET
ENV STRAVA_OAUTH_STATE_SECRET=$STRAVA_OAUTH_STATE_SECRET

ARG USE_FIRESTORE_STATE
ENV USE_FIRESTORE_STATE=$USE_FIRESTORE_STATE

ARG FIRESTORE_ATHLETES_COLLECTION
ENV FIRESTORE_ATHLETES_COLLECTION=$FIRESTORE_ATHLETES_COLLECTION

ARG FIRESTORE_PIPELINE_RUNS_COLLECTION
ENV FIRESTORE_PIPELINE_RUNS_COLLECTION=$FIRESTORE_PIPELINE_RUNS_COLLECTION

ARG GCS_KNOWLEDGE_BUCKET
ENV GCS_KNOWLEDGE_BUCKET=$GCS_KNOWLEDGE_BUCKET

ARG STRAVA_KNOWLEDGE_BUCKET
ENV STRAVA_KNOWLEDGE_BUCKET=$STRAVA_KNOWLEDGE_BUCKET

ARG LOCAL_KNOWLEDGE_ROOT
ENV LOCAL_KNOWLEDGE_ROOT=$LOCAL_KNOWLEDGE_ROOT

ARG INTERNAL_PIPELINE_TOKEN
ENV INTERNAL_PIPELINE_TOKEN=$INTERNAL_PIPELINE_TOKEN

# Expone el puerto 8080 (Cloud Run escucha en este puerto)
EXPOSE 8080

# Comando para ejecutar la aplicación con Gunicorn.
# Para SSE y peticiones largas en Cloud Run, usamos worker threaded y timeout infinito
# para evitar abortos del worker mientras se transmite la respuesta.
CMD ["gunicorn", "-b", "0.0.0.0:8080", "--worker-class", "gthread", "--threads", "8", "--workers", "1", "--timeout", "0", "--graceful-timeout", "30", "app:app"]